adventure_works_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1433
      database: AdventureWorks2019
      schema: data_models
      user: sa
      password: sQLserver@2019
      encrypt: false
